// <auto-generated />
using System;
using Kombats.Players.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kombats.Players.Infrastructure.Persistence.EF.Migrations
{
    [DbContext(typeof(PlayersDbContext))]
    [Migration("20260404055607_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("players")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kombats.Players.Domain.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Agility")
                        .HasColumnType("integer")
                        .HasColumnName("agility");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created");

                    b.Property<Guid>("IdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_id");

                    b.Property<int>("Intuition")
                        .HasColumnType("integer")
                        .HasColumnName("intuition");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("LevelingVersion")
                        .HasColumnType("integer")
                        .HasColumnName("leveling_version");

                    b.Property<int>("Losses")
                        .HasColumnType("integer")
                        .HasColumnName("losses");

                    b.Property<string>("Name")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("name");

                    b.Property<int>("OnboardingState")
                        .HasColumnType("integer")
                        .HasColumnName("onboarding_state");

                    b.Property<int>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.Property<long>("TotalXp")
                        .HasColumnType("bigint")
                        .HasColumnName("total_xp");

                    b.Property<int>("UnspentPoints")
                        .HasColumnType("integer")
                        .HasColumnName("unspent_points");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated");

                    b.Property<int>("Vitality")
                        .HasColumnType("integer")
                        .HasColumnName("vitality");

                    b.Property<int>("Wins")
                        .HasColumnType("integer")
                        .HasColumnName("wins");

                    b.HasKey("Id")
                        .HasName("pk_characters");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_characters_identity_id");

                    b.ToTable("characters", "players");
                });

            modelBuilder.Entity("Kombats.Players.Infrastructure.Messaging.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("MessageId")
                        .HasName("pk_inbox_messages");

                    b.ToTable("inbox_messages", "players");
                });
#pragma warning restore 612, 618
        }
    }
}
