parent=keycloak
import=common/keycloak

styles=css/login.css css/kombats.css
stylesCommon=web_components/webcomponents-lite.js node_modules/@patternfly/patternfly/patternfly.min.css node_modules/patternfly/dist/css/patternfly.min.css node_modules/patternfly/dist/css/patternfly-additions.min.css lib/pficon/pficon.css

meta=viewport==width=device-width,initial-scale=1

kcHtmlClass=kombats-html
kcBodyClass=kombats-body login-pf-page
