#!/usr/bin/env python3
"""Generate docker-compose.capacity-replicas.yml with N Battle replicas.

Phase C / Chapter 4 — replica generator for the capacity scan. Emits N
named Battle services (battle, battle-2, ... battle-N) — NOT
`docker compose --scale` — to preserve log determinism (see
docker-compose.multi-replica.yml header).

The first replica is the base `battle` service inherited from
docker-compose.yml; for N=1 this script writes a no-op overlay (empty
services block) and the existing single-replica `battle` service is
used as-is. For N>=2 the script appends battle-2 ... battle-N blocks
that mirror the existing battle-2 definition (env, network alias,
container name, depends_on) with only the index changed.

Cap: N must be 1..4. Stages 5-6 (500/1000 simul) are deliberately
out of Phase C scope — extending beyond 4 belongs to Chapter 5.

Usage:
    python scripts/generate-battle-replicas.py 2
    # writes docker-compose.capacity-replicas.yml in the repo root

Then chain it onto the compose stack:
    docker compose \\
        -f docker-compose.yml \\
        -f observability/docker-compose.observability.yml \\
        -f observability/docker-compose.observability.override.yml \\
        -f docker-compose.override.yml \\
        -f docker-compose.capacity.yml \\
        -f docker-compose.capacity-replicas.yml \\
        up -d --build
"""
from __future__ import annotations

import sys
from pathlib import Path

MAX_REPLICAS = 4
REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = REPO_ROOT / "docker-compose.capacity-replicas.yml"

HEADER = """# AUTO-GENERATED by scripts/generate-battle-replicas.py — DO NOT EDIT BY HAND.
#
# Phase C / Chapter 4 — N Battle replicas for the capacity scan.
# Named services (NOT docker compose --scale) — preserves per-container log
# determinism. Each extra replica advertises the `battle` network alias so
# Docker's embedded DNS round-robins lookups across all replicas.
#
# To regenerate:
#     python scripts/generate-battle-replicas.py <N>
# where N in 1..{max_replicas}. Stages 5-6 (>4 replicas) are Chapter 5 scope.
#
# Replica count baked into this file: N={n}
"""

EMPTY_BODY = "services: {}\n"

REPLICA_BLOCK_TEMPLATE = """  battle-{i}:
    build:
      context: .
      dockerfile: src/Kombats.Battle/Kombats.Battle.Bootstrap/Dockerfile
    container_name: kombats-battle-{i}
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8080"
      ConnectionStrings__PostgresConnection: "Host=postgres;Port=5432;Database=kombats;Username=postgres;Password=postgres;Maximum Pool Size=20;Minimum Pool Size=5;Connection Idle Lifetime=300"
      ConnectionStrings__Redis: "redis:6379,abortConnect=false"
      Keycloak__Authority: "http://keycloak:8080/realms/kombats"
      Keycloak__Audience: "kombats-api"
      Messaging__RabbitMq__Host: "rabbitmq"
      Messaging__RabbitMq__Port: "5672"
      Messaging__RabbitMq__Username: "guest"
      Messaging__RabbitMq__Password: "guest"
      Messaging__RabbitMq__VirtualHost: "/"
      Cors__AllowedOrigins__0: "http://localhost:5173"
      OpenTelemetry__OtlpEndpoint: "http://otel-collector:4317"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      default:
        aliases:
          - battle
    restart: unless-stopped
"""


def render(n: int) -> str:
    header = HEADER.format(max_replicas=MAX_REPLICAS, n=n)
    if n == 1:
        # No extra replicas — base `battle` service from docker-compose.yml
        # provides the single replica. Emit a no-op overlay so the chain
        # still works without conditional -f arguments.
        return header + "\n" + EMPTY_BODY
    blocks = [REPLICA_BLOCK_TEMPLATE.format(i=i) for i in range(2, n + 1)]
    return header + "\nservices:\n" + "\n".join(blocks)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(f"usage: {argv[0] if argv else 'generate-battle-replicas.py'} <N>", file=sys.stderr)
        print(f"  N: number of Battle replicas (1..{MAX_REPLICAS})", file=sys.stderr)
        return 2
    try:
        n = int(argv[1])
    except ValueError:
        print(f"error: N must be an integer, got {argv[1]!r}", file=sys.stderr)
        return 2
    if n < 1:
        print(f"error: N must be >= 1, got {n}", file=sys.stderr)
        return 2
    if n > MAX_REPLICAS:
        print(
            f"error: N={n} exceeds Phase C cap of {MAX_REPLICAS} replicas.\n"
            f"Stages 5-6 (500/1000 simul) belong to Chapter 5 — not Phase C scope.",
            file=sys.stderr,
        )
        return 2

    content = render(n)
    OUTPUT_PATH.write_text(content)
    print(f"wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} (N={n}, {len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
